
path: '/content/gdrive/My Drive/histopathology_mine' # dataset root dir
train: images/train # train images (relative to 'path')
val: images/val  # val images (relative to 'path')

# Classes
names:
  0: outside_roi
  1: tumor
  2: stroma
  3: lymphocytic_infiltrate
  4: necrosis_or_debris
  5: glandular_secretions
  6: blood
  7: exclude
  8: metaplasia_NOS
  9: fat
  10: plasma_cells
  11: other_immune_infiltrate
  12: mucoid_material
  13: normal_acinus_or_duct
  14: lymphatics
  15: undetermined
  16: nerve
  17: skin_adnexa
  18: blood_vessel
  19: angioinvasion
  20: dcis
  21: other