data: "../config/bcss_data.yaml"
epochs: 100
optimizer: 'AdamW'
plots: True
val: True
patience: 20
save_period: 20
classes: [1, 2, 3, 4, 5, 6, 9, 10, 11, 13, 14, 18]

lr0: 0.001
lrf: 0.01
momentum: 0.937
weight_decay: 0.0005
warmup_epochs: 3
warmup_momentum: 0.8