path: "/local/scratch/pz286/dl_histopathology"
train: "images/train"
val: "images/validation"
train_labels: "labels/train"
val_labels: "labels/validation"

# Classes
names:
  0: TA
  1: CB
  2: NFT
  3: tau_fragments