data: "../config/tau_data.yaml"
epochs: 300
optimizer: 'AdamW'
plots: True
val: True
patience: 20
save_period: 20

# hyperparameters saved from the best performance obtained throughout tuning for 100 iterations of 10 epochs each
lr0: 0.001
lrf: 0.01
#momentum: 0.89225
#weight_decay: 0.0003
#warmup_epochs: 4.77615
#warmup_momentum: 0.86454
#box: 7.08673
#cls: 0.41456
#dfl: 1.72313
#hsv_h: 0.01225
hsv_h: 0
#hsv_s: 0.40973
hsv_s: 0
#hsv_v: 0.24328
hsv_v: 0
#degrees: 36.35184
degrees: 0
#translate: 0.09625
translate: 0
#scale: 0.37703
scale: 0
shear: 0.0
perspective: 0.0
#flipud: 0.42503
flipud: 0
#fliplr: 0.66767
fliplr: 0
bgr: 0.0
#mosaic: 0.58041
mosaic: 0
mixup: 0.0
#copy_paste: 0.0
#dropout: 0.1
erasing: 0
crop_fraction: 0