data: "/local/scratch/pz286/dl_histopathology/config/tau_data.yaml"
epochs: 200
optimizer: 'AdamW'
plots: True
val: True
patience: 40 # increased from 20 to 40, to account for plateau period
save_period: 20
weight_decay: 0.0001

# hyperparameters saved from the best performance obtained throughout tuning for 100 iterations of 10 epochs each
lr0: 0.001
lrf: 0.01
hsv_h: 0
hsv_s: 0
hsv_v: 0
degrees: 0
translate: 0
scale: 0
shear: 0
perspective: 0
flipud: 0
fliplr: 0
bgr: 0
mosaic: 0
mixup: 0
copy_paste: 0
erasing: 0
crop_fraction: 0

# Disable RandAugment
auto_augment: False

# Custom augmentation settings
augment: True
custom_augment: True
clahe_params:
  p: 0.5               # 50% chance of applying CLAHE
  clip_limit: 1.0      # Conservative clip limit
  tile_grid_size: 8    # Grid size for local regions