data: "/local/scratch/pz286/dl_histopathology/config/tau_data.yaml"
epochs: 30
iterations: 10
optimizer: AdamW
plots: true
save: true
val: true

space:
  # Geometric augmentations
  degrees: [0.0, 45.0]     # Rotation range (current: 15)
  flipud: [0.0, 1.0]       # Vertical flip probability (current: 0.42503)

lr0: 0.0095
lrf: 0.01328

hsv_h: 0
hsv_s: 0
hsv_v: 0
perspective: 0.0
bgr: 0.0
mosaic: 0
mixup: 0.0
erasing: 0

translate: 0.1
fliplr: 0.5

scale: 0.47339
shear: 0.0
crop_fraction: 1.0
auto_augment: False
