data: "/local/scratch/pz286/dl_histopathology/config/tau_data.yaml"
epochs: 200
optimizer: 'AdamW'
plots: True
val: True
patience: 40 # increased from 20 to 40, to account for plateau period
save_period: 20
weight_decay: 0.0001

# hyperparameters saved from the best performance obtained throughout tuning for 100 iterations of 10 epochs each
lr0: 0.001
lrf: 0.01
hsv_h: 0.01225
hsv_s: 0.40973
hsv_v: 0.24328
degrees: 36.35184
translate: 0.09625
scale: 0.37703
shear: 0.0
perspective: 0.0
flipud: 0.42503
fliplr: 0.66767
bgr: 0.0
mosaic: 0
mixup: 0.0
copy_paste: 0.0
erasing: 0
crop_fraction: 0