data: "/local/scratch/pz286/dl_histopathology/config/tau_data.yaml"
epochs: 10
iterations: 100
optimizer: AdamW
plots: true
save: false
val: false
cache: true 
batch: -1
fraction: 0.3    # Use subset of data for faster tuning

space:
  # Learning rates
  lr0: [0.0001, 0.01]      # Initial learning rate range
  lrf: [0.01, 1.0]         # Final LR factor range
  
  # Geometric augmentations with proper ranges
  degrees: 
    min: 0.0
    max: 180.0
  
  shear:
    min: -180.0
    max: 180.0
  
  translate:
    min: 0.0
    max: 1.0
  
  scale:
    min: 0.0
    max: 1.0
  
  flipud:
    min: 0.0
    max: 1.0
  
  fliplr:
    min: 0.0
    max: 1.0

# Fixed parameters
lr0: 0.0095
lrf: 0.01328
hsv_h: 0
hsv_s: 0
hsv_v: 0
perspective: 0.0
bgr: 0.0
mosaic: 0
mixup: 0.0
erasing: 0
auto_augment: False