path: "../prepared_data/Tau"  # absolute path to dataset root dir
train: images/train  # train images (relative to 'path')
val: images/valid   # val images (relative to 'path' - also, keep it the same for simplicity for now)
train_labels: labels/train
val_labels: labels/valid

# Classes
names:
  0: TA
  1: CB
  2: NFT
  3: tau_fragments
