data: "/local/scratch/pz286/dl_histopathology/config/tau_data.yaml"
epochs: 10
iterations: 10
optimizer: AdamW
plots: true
save: false
val: false
cache: true 
batch: -1
fraction: 0.3    # Use subset of data for faster tuning

space:
  # Geometric transformations
  shear: [0.0, 2.5, 5.0, 7.5, 10.0]      # 5 values with 2.5 step
  degrees: [5.0, 15.0, 25.0, 35.0, 45.0]  # 5 values with 10° step
  flipud: [0.2, 0.4, 0.6, 0.8]            # 4 values with 0.2 step
  scale: [0.2, 0.4, 0.6, 0.8]             # 4 values with 0.2 step
  translate: [0.05, 0.1, 0.15, 0.2]       # 4 values with 0.05 step
  fliplr: [0.2, 0.4, 0.6, 0.8]            # 4 values with 0.2 step

# Fixed parameters
lr0: 0.0095
lrf: 0.01328
hsv_h: 0
hsv_s: 0
hsv_v: 0
perspective: 0.0
bgr: 0.0
mosaic: 0
mixup: 0.0
erasing: 0
auto_augment: False