data: "/local/scratch/pz286/dl_histopathology/config/tau_data.yaml"
epochs: 75  # Increase to get better convergence
iterations: 100  # Decrease to maintain reasonable total computation time
optimizer: 'AdamW'
plots: True
save: True
val: True

lr0: 0.001
lrf: 0.01

hsv_h: 0
hsv_s: 0
hsv_v: 0
perspective: 0.0
bgr: 0.0
mosaic: 0
mixup: 0.0
erasing: 0

degrees: 15
translate: 0.1
flipud: 0.42503
fliplr: 0.66767
scale: 0.5
shear: 5.0
auto_augment: False