data: "/local/scratch/pz286/dl_histopathology/config/tau_data_cortical.yaml"
epochs: 70
iterations: 50
optimizer: AdamW
plots: true
save: false
val: false
cache: true
batch: -1
fraction: 0.8    # Use subset of data for faster tuning

lr0: 0.0001
lrf: 0.01
hsv_h: 0
hsv_s: 0
hsv_v: 0
perspective: 0.0
bgr: 0.0
mosaic: 0
mixup: 0.0

erasing: 0
auto_augment: False

