path: "/local/scratch/pz286"  # changed to parent directory
train: images/train_per_region/cortical  
val: images/validation_per_region/cortical
test: images/test

# Classes
names:
  0: TA
  1: CB
  2: NFT
  3: tau_fragments