data: "/local/scratch/pz286/dl_histopathology/config/tau_data.yaml"
epochs: 200
optimizer: 'AdamW'
plots: True
val: True
batch: -1

weight_decay: 0.0005

lr0: 0.001
lrf: 0.01

hsv_h: 0
hsv_s: 0
hsv_v: 0
perspective: 0.0
bgr: 0.0
mosaic: 0
mixup: 0.0
erasing: 0

degrees: 1.34
translate: 0.206
flipud: 0.259
fliplr: 0.572
scale: 0.264
shear: 2.8
auto_augment: False